name: Build and Deploy
# NOTE: this .yml file is adapted (nearly wholesale) from 
#   https://github.com/tlienart/FranklinTemplates.jl/blob/master/src/templates/common/.github/workflows/deploy.yml
on:
  push:
    # NOTE:
    #   For a **project** site (username.github.io/project/), push things
    #     to the **master** branch and make sure to set the line below to
    # `   - master`; also, at the end of the file, change to `BRANCH: gh-pages`
    #
    #   For a **personal** site (username.github.io/), push things to a **dev**
    #     branch  and make sure to set the line  below to `- dev` this is
    #     because for user pages GitHub pages **requires** the deployment to be
    #     on the master branch; also, at the end of the file, change to
    #    `BRANCH: master`
    branches:
      - dev
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false
    # NOTE: Python is necessary for the pre-rendering (minification) step
    - name: Install python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    # NOTE: Here you can install dependencies such as matplotlib if you use
    # packages such as PyPlot.
    # - run: pip install matplotlib
    - name: Install Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: 1
    # NOTE
    #   The steps below ensure that NodeJS and Franklin are loaded then it
    #   installs highlight.js which is needed for the prerendering step
    #   (code highlighting + katex prerendering).
    #   Then the environment is activated and instantiated to install all
    #   Julia packages which may be required to successfully build your site.
    #   The last line should be `optimize()` though you may want to give it
    #   specific arguments, see the documentation or ?optimize in the REPL.
    #   The Sass additions ensure we get the style files right.
    - run: julia -e '
            using Pkg; Pkg.activate("."); Pkg.instantiate();
            using NodeJS; run(`$(npm_cmd()) install highlight.js`);
            using Sass;
            cd("_sass");
            Sass.compile_file("style.scss", "../_css/celeste.min.css"; output_style = Sass.compressed);
            cd("..");
            using Franklin;
            optimize()'
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v4
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # NOTE
        #   Set this to `BRANCH: gh-pages` for a **project** page and  to
        #   `BRANCH: master` for a **personal** page
        BRANCH: master
        FOLDER: __site
